
# Gem::Specification for Rails-test-serving-0.1.1
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: rails-test-serving
version: !ruby/object:Gem::Version 
  version: 0.1.1
platform: ruby
authors: 
- "Roman Le N\xC3\xA9grate"
autorequire: 
bindir: bin

date: 2008-11-17 00:00:00 +01:00
default_executable: 
dependencies: []

description: Makes unit tests of a Rails application run instantly
email: roman.lenegrate@gmail.com
executables: []

extensions: []

extra_rdoc_files: 
- lib/rails_test_serving.rb
- LICENSE
- README.rdoc
files: 
- lib/rails_test_serving.rb
- LICENSE
- Manifest
- Rakefile
- README.rdoc
- test/rails_test_serving_test.rb
- rails-test-serving.gemspec
has_rdoc: true
homepage: https://github.com/Roman2K/rails-test-serving
post_install_message: 
rdoc_options: 
- --main
- README.rdoc
- --inline-source
- --line-numbers
- --charset
- UTF-8
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: rails-test-serving
rubygems_version: 1.3.1
specification_version: 2
summary: Makes unit tests of a Rails application run instantly
test_files: 
- test/rails_test_serving_test.rb
